name: Translator

on:
  workflow_dispatch:
    inputs:
      subdomain:
        description: "Target subdomain (e.g., reference.aspose.net)"
        required: true
        default: 'reference.aspose.net'
      families:
        description: "Comma-separated list of families to process (e.g., words,cells,barcode)"
        required: true
        default: 'words,pdf,cells,imaging,barcode,tasks,ocr,html,zip,page,psd,tex'
      languages:
        description: "Comma-separated list of target languages (e.g., zh,es,fr)"
        required: true
        default: 'de,es,fr,ja,ko,ru,zh,ar,it,pt,pl,fa,id,cs,vi,tr,th,sv,el,uk,he'

permissions:
  contents: write       # for committing back to Aspose repo
  actions: read         # to fetch marketplace actions
  artifacts: write      # to upload/download artifacts

jobs:
  prepare-matrix:
    name: Prepare Family-Language Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Convert families and languages inputs to JSON array of objects
        id: set_matrix
        shell: bash
        run: |
          IFS=',' read -ra FAM_LIST <<< "${{ inputs.families }}"
          IFS=',' read -ra LANG_LIST <<< "${{ inputs.languages }}"
          elements=()
          for fam in "${FAM_LIST[@]}"; do
            fam="$(echo -n "$fam" | xargs)"
            [[ -z "$fam" ]] && continue
            for lang in "${LANG_LIST[@]}"; do
              lang="$(echo -n "$lang" | xargs)"
              [[ -z "$lang" ]] && continue
              elements+=("{\"family\": \"${fam}\", \"language\": \"${lang}\"}")
            done
          done
          json="[$(IFS=,; echo "${elements[*]}")]"
          echo "matrix=$json" >> $GITHUB_OUTPUT

  translate:
    name: Translate Markdown Files
    needs: prepare-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    permissions:
      contents: write
    steps:
      - name: Checkout aspose.net repository
        uses: actions/checkout@v3
        with:
          repository: Aspose/aspose.net
          path: aspose-net
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Checkout translationcache repository
        uses: actions/checkout@v3
        with:
          repository: smallize/translationcache
          path: translationcache
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-frontmatter mistune beautifulsoup4 pyyaml torch transformers sentencepiece

      - name: Configure Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Run AST Creator Script
        run: |
          python aspose-net/scripts/ast-translator/ast-creator.py \
            --input "aspose-net/content/${{ inputs.subdomain }}/${{ matrix.family }}"

      - name: Run AST Filter Script
        run: |
          python aspose-net/scripts/ast-translator/ast-filter.py \
            --input "aspose-net/ast/${{ inputs.subdomain }}/${{ matrix.family }}"

      - name: Run AST Translation with Watchdog
        shell: bash
        run: |
          # (existing watchdog logic unchanged)
          python aspose-net/scripts/ast-translator/ast-translator.py \
            --cache_folder aspose-net/translation \
            --device auto \
            --target_languages "${{ matrix.language }}" \
            --batch_size 10 \
            --existing_cache_folder translationcache

      - name: Merge and Push Updated Translation Cache
        shell: bash
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          # (existing cache merge logic unchanged)

      - name: Run AST2MD Converter Script
        run: |
          python aspose-net/scripts/ast-translator/ast2md-converter.py \
            --input "aspose-net/ast/${{ inputs.subdomain }}/${{ matrix.family }}" \
            --target_language ${{ matrix.language }} \
            --cache_folder translationcache

      - name: Upload translations artifact
        uses: actions/upload-artifact@v2
        with:
          name: translations-${{ matrix.family }}-${{ matrix.language }}
          path: aspose-net/content/${{ inputs.subdomain }}/${{ matrix.family }}

  merge-and-push:
    name: Merge & Push All Translations
    needs: translate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Aspose.net repository
        uses: actions/checkout@v3
        with:
          repository: Aspose/aspose.net
          path: aspose-net
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Download all translation artifacts
        uses: actions/download-artifact@v2
        with:
          path: merged

      - name: Merge into content folder
        shell: bash
        run: |
          SUBDOMAIN=${{ github.event.inputs.subdomain }}
          mkdir -p aspose-net/content/"$SUBDOMAIN"
          for art in merged/*; do
            cp -a "$art/." aspose-net/content/"$SUBDOMAIN"/
          done

      - name: Commit & Push Merge
        shell: bash
        run: |
          cd aspose-net
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add content/${{ github.event.inputs.subdomain }}
          if git diff --cached --quiet; then
            echo "No translation changes to commit."
            exit 0
          fi
          git commit -m "Auto-translate ${{ github.event.inputs.subdomain }}: all families & langs"
          BRANCH=${GITHUB_REF#refs/heads/}
          git push origin HEAD:$BRANCH