name: websites.aspose.net
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout theme repo
        uses: actions/checkout@main
        with:
          repository: Aspose/aspose.net
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.136.0'
          extended: true
      - name: Determine Base URL
        id: base-url
        run: |
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            echo "url=https://websites.aspose.net" >> $GITHUB_ENV
          else
            echo "url=https://websites-qa.aspose.net" >> $GITHUB_ENV
          fi
      - name: Build WWW
        run: hugo --config "./configs/websites.aspose.net.toml" -b "${{ env.url }}" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
      - name: Deploy WWW to S3
        run: hugo deploy --config "configs/websites.aspose.net.toml" --maxDeletes=-1 --target "${{ github.event.inputs.environment }}" --invalidateCDN --force
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
